STOP = 0
LEFT = 1
RIGHT = 2
UP = 3
DOWN = 4
PLACE_BOMB = 5

ACTIONS = (STOP, LEFT, RIGHT, UP, DOWN, PLACE_BOMB)
MOVE_ACTIONS = (STOP, LEFT, RIGHT, UP, DOWN)

# Matches engine/player.py action semantics.
ACTION_DELTAS = {
    STOP: (0, 0),
    LEFT: (-1, 0),
    RIGHT: (1, 0),
    UP: (0, -1),
    DOWN: (0, 1),
}

GRASS = 0
WALL = 1
BOX = 2
ITEM_RADIUS = 3
ITEM_CAPACITY = 4
WALKABLE_TILES = (GRASS, ITEM_RADIUS, ITEM_CAPACITY)

BOARD_SIZE = 13
BOMB_TIMER = 7
MAX_BOMB_RADIUS = 5
HORIZON = 10
FIRE_DURATION = 1
INF = 10**9
